pipeline {
  agent any
  parameters {
    string(name: 'projectName', defaultValue: 'psapp', description: 'Project name to launch containers into')
    string(name: 'version', defaultValue: 'latest', description: 'Version number for image')
  }

  stages {
     stage('Build docker image') {
        steps {
          dir('containers/database') {
            sh "docker build -t database:${version} ."
          }
        }
    }
    stage('Deploy Container To Openshift') {
      steps {
        sh "oc login https://localhost:8443 --username developer --password developer --insecure-skip-tls-verify=true"
	sh "cd openshift; oc apply -f database-deploymentconfig.yaml"
        #sh "oc project ${projectName} || oc new-project ${projectName}"
        #sh "oc new-app database -l version=${version}"
      }
    }
  }
}
