FROM maven:3.6.3-jdk-11 AS compile
ADD . /usr/src/mymaven
WORKDIR /usr/src/mymaven
RUN mvn -Dmaven.test.skip=true package
RUN ls /usr/src/mymaven/target

FROM openjdk:11-jdk
MAINTAINER Neueda and TPS
LABEL Version="1.0.0"
LABEL Description="Docker container to run Martins trade app"
EXPOSE 8080 7091 7036

# Add monitoring
RUN mkdir -p /mon/log
RUN wget https://www.dropbox.com/s/gtsutpi79jdwkdj/geneos-netprobe-5.8.2-linux-x64.tar.gz?dl=0 -O /tmp/geneos-netprobe-5.8.2.linux-x64.tar.gz
RUN cd /mon && tar xvf /tmp/geneos-netprobe-5.8.2.linux-x64.tar.gz
RUN wget https://artifacts.elastic.co/downloads/logstash/logstash-8.3.2-linux-x86_64.tar.gz -O /tmp/logstash.tgz
RUN cd /mon && tar xvf /tmp/logstash.tgz
RUN mkdir /mon/logstash-8.3.2/conf
COPY logstash/conf/* /mon/logstash-8.3.2/conf/
# RUN sed -i 's/^-XX:+UseParNewGC/#-XX:+UseParNewGC/' /mon/logstash-6.2.4/config/jvm.options

# Add Prometheus
RUN wget https://github.com/ncabatoff/process-exporter/releases/download/v0.7.5/process-exporter-0.7.5.linux-amd64.tar.gz -O /tmp/process-exporter-0.7.5.linux-amd64.tar.gz
RUN mkdir /opt/exporters
RUN cd /opt/exporters;
RUN tar xvf /tmp/process-exporter-0.7.5.linux-amd64.tar.gz
RUN mv process-exporter-0.7.5.linux-amd64/process-exporter /opt/exporters/process-exporter
RUN rm -rf process-exporter-0.7.5.linux-amd64
RUN rm -f process-exporter-0.7.5.linux-amd64.tar.gz
COPY process-exporter.conf /opt/exporters
RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.2.0/node_exporter-1.2.0.linux-amd64.tar.gz -O /tmp/node_exporter-1.2.0.linux-amd64.tar.gz
RUN cd /opt/exporters; tar xvf /tmp/node_exporter-1.2.0.linux-amd64.tar.gz; mv node*/node_exporter /opt/exporters/node_exporter
RUN rm -rf /tmp/node_exporter-1.2.0.linux-amd64.tar.gz /opt/exporters/node_exporter-*
RUN wget https://github.com/dundee/disk_usage_exporter/releases/download/v0.1.0/disk_usage_exporter_linux_amd64.tgz -O /tmp/disk_usage_exporter_linux_amd64.tgz
RUN cd /opt/exporters; tar xvf /tmp/disk_usage_exporter_linux_amd64.tgz; mv disk* disk_usage_exporter
COPY disk_usage_exporter.yaml /opt/exporters/disk_usage_exporter.yaml
EXPOSE 9100
EXPOSE 9995
EXPOSE 9256
EXPOSE 8080


# Add application
RUN mkdir /app
COPY --from=compile /usr/src/mymaven/target/trade-app-1.0.0-exec.jar /app/
RUN mkdir /app/config
COPY application.properties /app/config/
COPY application.properties /app/
COPY startmon.sh /app/start.sh
RUN chmod +x /app/start.sh
RUN ls -R /app
WORKDIR /app
ENTRYPOINT [ "./start.sh" ]